Here, I would like to show that we can just input any phylogenetic tree, designate a time and proportion of migration, and get an msprime sim.

In [80]:
import toytree
import phymsim
import numpy as np
print(toytree.__version__)
print(phymsim.__version__)

1.0.0
0.0.1-dev


### The species tree

In [81]:
# single-population random coalescent tree 
tree = toytree.rtree.coaltree(5, seed=333).mod.node_scale_root_height(1.5)

# set node Ne 
np.random.seed(3334)
for node in tree.treenode.traverse():
    node.add_feature("Ne", np.random.uniform(250000, 1000000))

# plot with Ne on edges
edges = np.array(tree.get_edge_values("Ne"))
tree.draw(ts='c', edge_widths=list(edges / edges.min() * 2));

<svg class="toyplot-canvas-Canvas" height="250.0px" id="t01176596a539495eaf76e47649bf71b6" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 350.0 250.0" width="350.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> idx: 0
name: r0
dist: 0.3071
support: 100
Ne: 589071.8302
height: 0.0000 0 idx: 1
name: r1
dist: 0.3071
support: 100
Ne: 639218.9531
height: 0.0000 1 idx: 2
name: r2
dist: 0.5409
support: 100
Ne: 881003.5309
height: 0.0000 2 idx: 3
name: r3
dist: 0.9246
support: 100
Ne: 985415.5348
height: 0.0000 3 idx: 4
name: r4
dist: 1.5000
support: 100
Ne: 454397.1735
height: 0.0000 4 idx: 5
name: 5
dist: 0.2338
support: 100
Ne: 250329.0493
height: 0.3071 5 idx: 6
name: 6
dist: 0.3837
support: 100
Ne: 623296.2787
height: 0.5409 6 idx: 7
name: 7
dist: 0.5754
support: 100
Ne: 732132.3531
height: 0.9246 7 idx: 8
name: 8
dist: 0.0004
support: 100
Ne: 899971.7090
height: 1.5000 8 0.0 0.8 1.5

### simulation object

In [105]:
# init a sim object ()
mod = phymsim.Model(tree, );


In [99]:
# takes node idxs as tip labels
mod.tree.get_tip_labels()

[0, 1, 2, 3, 4]

In [100]:
# can access original tip labels as well
mod.treeorig.get_tip_labels()

['r0', 'r1', 'r2', 'r3', 'r4']

### returns a treesequence dataframe and sequence alignment array.

It's not great to have an object that variably returns one or two results. If you want to have it sometimes not return the other it should still return None for it, that way you can always capture the result with the same code. 

In [87]:
# simulate the results
gt_df2, seqs2 = mod.run_locus(50000, seqgen=True);

It would be nice if the DF recorded how many SNPs are in each window as well (see SNP count code below).

In [88]:
# the tree sequence DF
print(gt_df2.shape)
gt_df2.head()

(315, 4)


starts       stops  bps  \
0    0.000000   81.086927   81   
1   81.086927  184.401032  103   
2  184.401032  461.543433  278   
3  461.543433  521.749992   60   
4  521.749992  658.583595  137   

                                             newicks  
0  ((r2:966027.76357754739001,r4:966027.763577547...  
1  (((r0:210078.66077706395299,r1:210078.66077706...  
2  (((r3:493060.97795964800753,(r1:311496.9206811...  
3  (r4:4397725.01832654513419,((r3:493060.9779596...  
4  (r4:4060974.59099883772433,((r3:493060.9779596...

In [89]:
# the first 5 trees
mtre = toytree.mtree(gt_df2.newicks.tolist())
mtre.draw_tree_grid(tree_style='c', shared_axis=True);

<svg class="toyplot-canvas-Canvas" height="250.0px" id="t0295bc08b6f64a72bfa9f4e10e963325" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 800.0 250.0" width="800.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> idx: 0
name: r1
dist: 210078.6608
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r0
dist: 210078.6608
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r3
dist: 1142724.8562
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r4
dist: 966027.7636
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r2
dist: 966027.7636
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 932646.1954
support: 100
Ne: 
height: 210078.6608 5 idx: 6
name: 6
dist: 3589365.3882
support: 100
Ne: 
height: 1142724.8562 6 idx: 7
name: 7
dist: 3766062.4808
support: 100
Ne: 
height: 966027.7636 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 4732090.2444 8 idx: 0
name: r3
dist: 493060.9780
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r2
dist: 493060.9780
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r1
dist: 210078.6608
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r0
dist: 210078.6608
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r4
dist: 4732090.2444
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 649663.8782
support: 100
Ne: 
height: 493060.9780 5 idx: 6
name: 6
dist: 932646.1954
support: 100
Ne: 
height: 210078.6608 6 idx: 7
name: 7
dist: 3589365.3882
support: 100
Ne: 
height: 1142724.8562 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 4732090.2444 8 idx: 0
name: r2
dist: 311496.9207
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r1
dist: 311496.9207
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r3
dist: 493060.9780
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r0
dist: 1142724.8562
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r4
dist: 4732090.2444
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 181564.0573
support: 100
Ne: 
height: 311496.9207 5 idx: 6
name: 6
dist: 649663.8782
support: 100
Ne: 
height: 493060.9780 6 idx: 7
name: 7
dist: 3589365.3882
support: 100
Ne: 
height: 1142724.8562 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 4732090.2444 8 idx: 0
name: r2
dist: 311496.9207
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r1
dist: 311496.9207
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r3
dist: 493060.9780
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r0
dist: 1142724.8562
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r4
dist: 4397725.0183
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 181564.0573
support: 100
Ne: 
height: 311496.9207 5 idx: 6
name: 6
dist: 649663.8782
support: 100
Ne: 
height: 493060.9780 6 idx: 7
name: 7
dist: 3255000.1621
support: 100
Ne: 
height: 1142724.8562 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 4397725.0183 8 idx: 0
name: r2
dist: 311496.9207
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r1
dist: 311496.9207
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r3
dist: 493060.9780
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r0
dist: 1142724.8562
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r4
dist: 4060974.5910
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 181564.0573
support: 100
Ne: 
height: 311496.9207 5 idx: 6
name: 6
dist: 649663.8782
support: 100
Ne: 
height: 493060.9780 6 idx: 7
name: 7
dist: 2918249.7348
support: 100
Ne: 
height: 1142724.8562 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 4060974.5910 8 0 2366045 4732090

In [90]:
# 5 random trees
mtre = toytree.mtree(gt_df2.newicks.sample(5).tolist())
mtre.draw_tree_grid(tree_style='c', shared_axis=True);

<svg class="toyplot-canvas-Canvas" height="250.0px" id="tb8172ce4bb5f477394a8325ce3b60a0a" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 800.0 250.0" width="800.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> idx: 0
name: r1
dist: 229612.4743
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r0
dist: 229612.4743
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r2
dist: 753037.4778
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r4
dist: 986536.7790
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r3
dist: 4377797.4975
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 523425.0035
support: 100
Ne: 
height: 229612.4743 5 idx: 6
name: 6
dist: 233499.3013
support: 100
Ne: 
height: 753037.4778 6 idx: 7
name: 7
dist: 3391260.7185
support: 100
Ne: 
height: 986536.7790 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 4377797.4975 8 idx: 0
name: r2
dist: 753037.4778
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r1
dist: 753037.4778
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r3
dist: 976860.8093
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r4
dist: 999156.1885
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r0
dist: 1621579.2203
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 223823.3316
support: 100
Ne: 
height: 753037.4778 5 idx: 6
name: 6
dist: 22295.3791
support: 100
Ne: 
height: 976860.8093 6 idx: 7
name: 7
dist: 622423.0319
support: 100
Ne: 
height: 999156.1885 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 1621579.2203 8 idx: 0
name: r3
dist: 741173.3108
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r2
dist: 741173.3108
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r4
dist: 1126988.5429
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r1
dist: 231062.6361
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r0
dist: 231062.6361
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 385815.2321
support: 100
Ne: 
height: 741173.3108 5 idx: 6
name: 6
dist: 1720527.3872
support: 100
Ne: 
height: 1126988.5429 6 idx: 7
name: 7
dist: 2616453.2939
support: 100
Ne: 
height: 231062.6361 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 2847515.9301 8 idx: 0
name: r1
dist: 285061.1552
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r0
dist: 285061.1552
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r2
dist: 456822.6591
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r3
dist: 866784.9676
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r4
dist: 5440887.4500
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 171761.5039
support: 100
Ne: 
height: 285061.1552 5 idx: 6
name: 6
dist: 409962.3085
support: 100
Ne: 
height: 456822.6591 6 idx: 7
name: 7
dist: 4574102.4824
support: 100
Ne: 
height: 866784.9676 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 5440887.4500 8 idx: 0
name: r3
dist: 2448671.7282
support: 100
Ne: 
height: 0.0000 0 idx: 1
name: r2
dist: 2448671.7282
support: 100
Ne: 
height: 0.0000 1 idx: 2
name: r4
dist: 2547858.7859
support: 100
Ne: 
height: 0.0000 2 idx: 3
name: r1
dist: 367873.8173
support: 100
Ne: 
height: 0.0000 3 idx: 4
name: r0
dist: 367873.8173
support: 100
Ne: 
height: 0.0000 4 idx: 5
name: 5
dist: 99187.0577
support: 100
Ne: 
height: 2448671.7282 5 idx: 6
name: 6
dist: 82650.3195
support: 100
Ne: 
height: 2547858.7859 6 idx: 7
name: 7
dist: 2262635.2882
support: 100
Ne: 
height: 367873.8173 7 idx: 8
name: 8
dist: 1.0000
support: 100
Ne: 
height: 2630509.1054 8 0 2720444 5440887

In [91]:
# the sequence dict
seqs2

{'r2': array([0, 2, 1, ..., 3, 1, 2], dtype=int8),
 'r4': array([3, 1, 1, ..., 2, 2, 2], dtype=int8),
 'r3': array([1, 1, 2, ..., 1, 3, 3], dtype=int8),
 'r0': array([2, 2, 1, ..., 0, 1, 3], dtype=int8),
 'r1': array([2, 0, 3, ..., 0, 1, 2], dtype=int8)}

In [94]:
# since tips are idx labels (0,1,2,3) maybe a 2d array is better
phy = np.vstack(list(seqs2[i] for i in sorted(seqs2)))
print(phy.shape)
print(phy)

(5, 50000)
[[2 2 1 ... 0 1 3]
 [2 0 3 ... 0 1 2]
 [0 2 1 ... 3 1 2]
 [1 1 2 ... 1 3 3]
 [3 1 1 ... 2 2 2]]


In [95]:
# then it's easy to pull out SNPs
snps = phy[:, np.any(phy != phy[0], axis=0)]
print(snps.shape)
print(snps)

(5, 49631)
[[2 2 1 ... 0 1 3]
 [2 0 3 ... 0 1 2]
 [0 2 1 ... 3 1 2]
 [1 1 2 ... 1 3 3]
 [3 1 1 ... 2 2 2]]


## compare the in-house sequence simulation with seqgen

### simulate 25 sequences on our tree with seqgen



In [16]:
sumlists1 = []
for oneloop in range(25):
    gt_df1, seqs1 = mod.run_locus(50000,seqgen=True)
    gt_df1
    sum_list = [np.sum(seqs1['r0'] == seqs1['r1']),
     np.sum(seqs1['r0'] == seqs1['r2']),
     np.sum(seqs1['r0'] == seqs1['r3']),
     np.sum(seqs1['r0'] == seqs1['r4']),
     np.sum(seqs1['r1'] == seqs1['r2']),
     np.sum(seqs1['r1'] == seqs1['r3']),
     np.sum(seqs1['r1'] == seqs1['r4']),
     np.sum(seqs1['r2'] == seqs1['r3']),
     np.sum(seqs1['r2'] == seqs1['r4']),
     np.sum(seqs1['r3'] == seqs1['r4'])]
    sumlists1.append(sum_list)
    print(oneloop)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


### simulate 25 sequences on our tree with the in-house simulation

In [17]:
sumlists2 = []
for oneloop in range(25):
    gt_df1, seqs1 = mod.run_locus(50000,seqgen=False)
    sum_list = [np.sum(seqs1['r0'] == seqs1['r1']),
     np.sum(seqs1['r0'] == seqs1['r2']),
     np.sum(seqs1['r0'] == seqs1['r3']),
     np.sum(seqs1['r0'] == seqs1['r4']),
     np.sum(seqs1['r1'] == seqs1['r2']),
     np.sum(seqs1['r1'] == seqs1['r3']),
     np.sum(seqs1['r1'] == seqs1['r4']),
     np.sum(seqs1['r2'] == seqs1['r3']),
     np.sum(seqs1['r2'] == seqs1['r4']),
     np.sum(seqs1['r3'] == seqs1['r4'])]
    sumlists2.append(sum_list)
    print(oneloop)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


### compare the sequence matches for each taxa

In [22]:
print(np.mean([i[0] for i in sumlists1]))
print(np.mean([i[0] for i in sumlists2]))

19372.0
19897.88


In [24]:
print(np.mean([i[1] for i in sumlists1]))
print(np.mean([i[1] for i in sumlists2]))

16473.92
16348.84


In [26]:
print(np.mean([i[2] for i in sumlists1]))
print(np.mean([i[2] for i in sumlists2]))

15259.6
15240.24


In [27]:
print(np.mean([i[3] for i in sumlists1]))
print(np.mean([i[3] for i in sumlists2]))

15248.64
15272.88


In [28]:
print(np.mean([i[4] for i in sumlists1]))
print(np.mean([i[4] for i in sumlists2]))

16400.16
16352.04


In [29]:
print(np.mean([i[5] for i in sumlists1]))
print(np.mean([i[5] for i in sumlists2]))

15375.96
15223.4


In [30]:
print(np.mean([i[6] for i in sumlists1]))
print(np.mean([i[6] for i in sumlists2]))

15220.04
15172.12


In [31]:
print(np.mean([i[7] for i in sumlists1]))
print(np.mean([i[7] for i in sumlists2]))

15296.56
15289.84


In [32]:
print(np.mean([i[8] for i in sumlists1]))
print(np.mean([i[8] for i in sumlists2]))

15204.88
15213.92


In [33]:
print(np.mean([i[9] for i in sumlists1]))
print(np.mean([i[9] for i in sumlists2]))

15200.2
15160.92


## Make a tree where node values correspond to thetas:

In [184]:
tree = toytree.rtree.coaltree(5)
tree.draw(node_labels=True, node_sizes=15, tip_labels_align=True);

<svg class="toyplot-canvas-Canvas" height="275.0px" id="tb045d112bc374159af621f69ba07e33f" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 260.0 275.0" width="260.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> r0 r1 r2 r3 r4 idx: 0
name: r0
dist: 0.1646
support: 100
height: 0.0000 0 idx: 1
name: r1
dist: 0.1646
support: 100
height: 0.0000 1 idx: 2
name: r2
dist: 0.2394
support: 100
height: 0.0000 2 idx: 3
name: r3
dist: 0.0477
support: 100
height: 0.0000 3 idx: 4
name: r4
dist: 0.0477
support: 100
height: 0.0000 4 idx: 5
name: 5
dist: 0.0747
support: 100
height: 0.1646 5 idx: 6
name: 6
dist: 0.1023
support: 100
height: 0.2394 6 idx: 7
name: 7
dist: 0.2939
support: 100
height: 0.0477 7 idx: 8
name: 8
dist: 0.0001
support: 100
height: 0.3416 8

In [185]:
idx = 0
Nes=[10000,20000,30000,40000,50000,60000,70000,80000,90000]
for node in tree.treenode.traverse():
    node.add_feature('Ne', Nes[idx])
    idx+=1

In [186]:
tree.draw(node_labels=tree.get_node_values("Ne", True, True), node_sizes=15, tip_labels_align=True);

<svg class="toyplot-canvas-Canvas" height="275.0px" id="tb223b92ddc8a4811b91cb9f171bcd1b0" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 260.0 275.0" width="260.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> r0 r1 r2 r3 r4 90000 80000 60000 50000 40000 70000 30000 20000 10000

In [196]:
# get theta values from nodes
norm_thetas = list(np.array(tree.get_edge_values("Ne")) / 10000)

# plot as edge widths
tree.draw(ts='c', edge_widths=norm_thetas, tip_labels=True);

<svg class="toyplot-canvas-Canvas" height="260.0px" id="t77c61227996c443ca2477c80c635015f" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 350.0 260.0" width="350.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> r0 r1 r2 r3 r4 idx: 0
name: r0
dist: 0.1646
support: 100
height: 0.0000
Ne: 90000 0 idx: 1
name: r1
dist: 0.1646
support: 100
height: 0.0000
Ne: 80000 1 idx: 2
name: r2
dist: 0.2394
support: 100
height: 0.0000
Ne: 60000 2 idx: 3
name: r3
dist: 0.0477
support: 100
height: 0.0000
Ne: 50000 3 idx: 4
name: r4
dist: 0.0477
support: 100
height: 0.0000
Ne: 40000 4 idx: 5
name: 5
dist: 0.0747
support: 100
height: 0.1646
Ne: 70000 5 idx: 6
name: 6
dist: 0.1023
support: 100
height: 0.2394
Ne: 30000 6 idx: 7
name: 7
dist: 0.2939
support: 100
height: 0.0477
Ne: 20000 7 idx: 8
name: 8
dist: 0.0001
support: 100
height: 0.3416
Ne: 10000 8 0.0 0.2 0.3

In [32]:
mod = phymsim.Model(tree,theta = 0.1,mut=1e-8)

In [33]:
mod._get_demography()

[{'type': 'mass_migration', 'time': 73247, 'source': 4, 'dest': 3, 'proportion': 1.0},
 {'type': 'population_parameters_change', 'time': 73247, 'growth_rate': None, 'initial_size': 20000, 'population': 3},
 {'type': 'mass_migration', 'time': 465510, 'source': 1, 'dest': 0, 'proportion': 1.0},
 {'type': 'population_parameters_change', 'time': 465510, 'growth_rate': None, 'initial_size': 70000, 'population': 0},
 {'type': 'mass_migration', 'time': 1212747, 'source': 2, 'dest': 0, 'proportion': 1.0},
 {'type': 'population_parameters_change', 'time': 1212747, 'growth_rate': None, 'initial_size': 30000, 'population': 0},
 {'type': 'mass_migration', 'time': 1448542, 'source': 3, 'dest': 0, 'proportion': 1.0},
 {'type': 'population_parameters_change', 'time': 1448542, 'growth_rate': None, 'initial_size': 10000, 'population': 0}]

In [34]:
[i.initial_size for i in mod._get_popconfig()] # this tells us the size of each population index

[90000, 80000, 60000, 50000, 40000]

In [35]:
gt_df2, seqs2 = mod.run_locus(50000,seqgen=False)
gt_df2

starts         stops   bps  \
0       0.000000   1674.852893  1675   
1    1674.852893   3521.611228  1847   
2    3521.611228   4479.862529   958   
3    4479.862529   4611.946795   132   
4    4611.946795   5361.744518   750   
5    5361.744518   5999.551110   638   
6    5999.551110   7611.306048  1611   
7    7611.306048   9469.025468  1858   
8    9469.025468  10423.312467   954   
9   10423.312467  11512.812265  1090   
10  11512.812265  15794.588885  4282   
11  15794.588885  16759.469422   964   
12  16759.469422  19838.154425  3079   
13  19838.154425  22261.229652  2423   
14  22261.229652  22765.106585   504   
15  22765.106585  23476.519942   712   
16  23476.519942  24267.504684   791   
17  24267.504684  25666.677446  1399   
18  25666.677446  26530.122041   863   
19  26530.122041  27278.594237   749   
20  27278.594237  27929.009736   650   
21  27929.009736  28671.512864   743   
22  28671.512864  30394.846033  1723   
23  30394.846033  31731.531043  1337   
24  31731.531043  31776.550315    45   
25  31776.550315  31923.588827   147   
26  31923.588827  32076.610504   153   
27  32076.610504  36148.503280  4072   
28  36148.503280  36271.689002   123   
29  36271.689002  37431.229159  1159   
30  37431.229159  39738.208717  2307   
31  39738.208717  39913.945969   176   
32  39913.945969  41431.596943  1518   
33  41431.596943  42894.615709  1463   
34  42894.615709  45995.566783  3101   
35  45995.566783  46807.821059   812   
36  46807.821059  47556.509147   749   
37  47556.509147  49178.326258  1621   
38  49178.326258  50000.000000   822   

                                              newicks  
0   ((r3:79277.25752043664397,r4:79277.25752043664...  
1   ((r3:79277.25752043664397,r4:79277.25752043664...  
2   ((r3:79277.25752043664397,r4:79277.25752043664...  
3   ((r3:79277.25752043664397,r4:79277.25752043664...  
4   ((r3:79277.25752043664397,r4:79277.25752043664...  
5   ((r3:79277.25752043664397,r4:79277.25752043664...  
6   ((r3:79277.25752043664397,r4:79277.25752043664...  
7   ((r3:79277.25752043664397,r4:79277.25752043664...  
8   ((r3:79277.25752043664397,r4:79277.25752043664...  
9   ((r3:79277.25752043664397,r4:79277.25752043664...  
10  ((r3:79277.25752043664397,r4:79277.25752043664...  
11  ((r2:1362426.01866096490994,(r0:620115.8634960...  
12  ((r2:1362426.01866096490994,(r0:491520.2289699...  
13  ((r3:85614.33407134485606,r4:85614.33407134485...  
14  ((r3:85614.33407134485606,r4:85614.33407134485...  
15  ((r3:85614.33407134485606,r4:85614.33407134485...  
16  ((r3:85614.33407134485606,r4:85614.33407134485...  
17  ((r3:85614.33407134485606,r4:85614.33407134485...  
18  ((r3:85614.33407134485606,r4:85614.33407134485...  
19  ((r3:85614.33407134485606,r4:85614.33407134485...  
20  ((r3:85614.33407134485606,r4:85614.33407134485...  
21  ((r3:85614.33407134485606,r4:85614.33407134485...  
22  ((r3:85614.33407134485606,r4:85614.33407134485...  
23  ((r2:1264575.99577234196477,(r0:491520.2289699...  
24  ((r2:1264575.99577234196477,(r0:674358.8390784...  
25  ((r2:1264575.99577234196477,(r0:706114.2210653...  
26  ((r2:1264575.99577234196477,(r0:823495.1576408...  
27  ((r2:1264575.99577234196477,(r0:471541.0863182...  
28  ((r3:79277.25752043664397,r4:79277.25752043664...  
29  ((r3:79277.25752043664397,r4:79277.25752043664...  
30  ((r3:79277.25752043664397,r4:79277.25752043664...  
31  ((r2:1306493.21926353638992,(r0:471541.0863182...  
32  ((r3:107614.70814426591096,r4:107614.708144265...  
33  ((r3:107614.70814426591096,r4:107614.708144265...  
34  ((r3:107614.70814426591096,r4:107614.708144265...  
35  ((r3:107614.70814426591096,r4:107614.708144265...  
36  ((r3:107614.70814426591096,r4:107614.708144265...  
37  ((r3:107614.70814426591096,r4:107614.708144265...  
38  ((r2:1249197.02724426053464,(r0:579008.0190996...

In [40]:
toytree.tree(gt_df2.newicks[23]).draw()

(<toyplot.canvas.Canvas at 0x120d519e8>,
 <toyplot.coordinates.Cartesian at 0x120d51a58>)

<svg class="toyplot-canvas-Canvas" height="275.0px" id="t50073b5838b94d76b419a855d7f6679f" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 260.0 275.0" width="260.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> r1 r0 r2 r4 r3

### Species trees should be described in units of generations -- this is because the tips will line up at the front! This is not assured in coalescent unit trees

5000
5000
5000
5000
5000
